name: Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y gettext

      - name: tx push / pull
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          TX_TOKEN=${{ secrets.TX_TOKEN }} make transifex_sync # push
          TX_TOKEN=${{ secrets.TX_TOKEN }} make transifex_pull

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update .tx/config

      - name: build
        run: |
          make html
          touch build/html/.nojekyll

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/maste' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/html
