name: Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y gettext

      - name: tx push / pull
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/move_away_from_travis' }}
        run: |
          make gettext
          tx config mapping-bulk --project qwat-doc --file-extension '.pot' --source-file-dir i18n/pot --source-lang en --type PO --expression 'i18n/<lang>/{filepath}/{filename}.po' --execute
          TX_TOKEN=${{ secrets.TX_TOKEN }} tx push -s
          TX_TOKEN=${{ secrets.TX_TOKEN }} make transifex_pull

      - name: build
        run: |
          make html
          touch build/html/.nojekyll

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/move_away_from_travis' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/html
