name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Python
          pip install -r requirements.txt
          sudo apt-get install -y gettext
          # Go
          curl -OL https://github.com/transifex/cli/releases/download/v1.3.1/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz

      - name: Pull then push translation strings
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
          # TX_TOKEN: "super_secret_token"
          PROBE: 1
        run: |
          echo $GITHUB_CONTEXT >> context.txt
          echo $PROBE >> probe.txt
          echo $TX_TOKEN >> token.txt
          TX_TOKEN=$TX_TOKEN PROBE=$PROBE make transifex_pull
          TX_TOKEN=$TX_TOKEN PROBE=$PROBE make transifex_push

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update .tx/config

      - name: build
        run: |
          make html
          touch build/html/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/html

      - name: tmate
        if: failure()
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        uses: m-kuhn/action-tmate@patch-1
